server:
  port: 8081

spring:
  application:
    name: "CleanArchitecture"
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: cleanarch
  kafka:
    group-id: jfbatis
    enabled: true
    topic:
      consumer:
        customer: customer
      producer:
        delivery: delivery
    bootstrap-servers:
      localhost:9092

jfb:
  client:
    address:
      url: http://localhost:8088/addresses
