spring:
  application:
    name: "CleanArchitecture"
  data:
    mongodb:
      uri: mongodb://localhost:27017/cleanarch
  kafka:
    group-id: jfbatis
    enabled: true
    topic:
      consumer:
        customer: customer
      producer:
        delivery: delivery
    bootstrap-servers:
      localhost:9092

jfb:
  client:
    address:
      url: http://localhost:8082/addresses
